apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptreatmentofferingdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IPTreatmentOffering
  template:
    metadata:
      labels:
        app: IPTreatmentOffering
    spec:
      containers:
      - name: iptreatmentoffering
        image: iptreatmentmanagementcr1.azurecr.io/iptreatmentofferingrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: iptreatmentofferingsn 

---
apiVersion: v1
kind: Service
metadata:
  name: iptreatmentoffering
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: IPTreatmentOffering